export const LOG_IN = 'LOGIN';
export const LOG_OUT = 'LOGOUT';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const TOGGLE_IS_ADDING = 'TOGGLE_IS_ADDING';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const LOAD_TERM_SUCCESS = 'LOAD_TERM_SUCCESS';
export const LOAD_ABOUT_SUCCESS = 'LOAD_ABOUT_SUCCESS';

export const LOAD_CATS_SUCCESS = 'LOAD_CATS_SUCCESS';
export const UPDATE_CAT_SUCCESS = 'UPDATE_CAT_SUCCESS';
export const CREATE_CAT_SUCCESS = 'CREATE_CAT_SUCCESS';
export const DELETE_CAT_SUCCESS = 'DELETE_CAT_SUCCESS';

export const LOAD_ADV_SUCCESS = 'LOAD_ADV_SUCCESS';
export const UPDATE_ADV_SUCCESS = 'UPDATE_ADV_SUCCESS';
export const CREATE_ADV_SUCCESS = 'CREATE_ADV_SUCCESS';
export const DELETE_ADV_SUCCESS = 'DELETE_ADV_SUCCESS';