export { default as Contact } from './Contact';
export { default as DocumentPage } from './DocumentPage';
export { default as Avatar } from './Avatar';
export { default as UploadeImage } from './UploadeImage';
export { default as IndentilyCard } from './IndentilyCard';
export { default as InfoUser } from './InfoUser';
export { default as Map } from './Map';
export { default as BusinessRegistration } from './BusinessRegistration';
export { default as Categories } from './Categories';
